FROM ubuntu

ARG DEBIAN_FRONTEND=noninteractive

ARG user

ENV OSSH_USER ${user:-git}

ARG uid

ENV OSSH_UID ${uid:-1000}

ARG gid

ENV OSSH_GID ${gid:-1000}

RUN apt-get update&&apt-get install -y openssh-server git rsync locales pwgen vim php

RUN locale-gen zh_TW.UTF-8

RUN mkdir /var/run/sshd
RUN sed -ri 's/^#?PermitRootLogin\s+.*/PermitRootLogin yes/' /etc/ssh/sshd_config && \
    sed -ri 's/UsePAM yes/#UsePAM yes/g' /etc/ssh/sshd_config && \
    sed -ri 's/#AuthorizedKeysFile/AuthorizedKeysFile/g' /etc/ssh/sshd_config && \
    sed -ri 's/#PasswordAuthentication yes/PasswordAuthentication no/g' /etc/ssh/sshd_config

RUN mkdir /root/.ssh

RUN apt-get clean &&  rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN addgroup --gid ${OSSH_GID} ${OSSH_USER}&&adduser --quiet --uid ${OSSH_UID} --gid ${OSSH_GID} --disabled-password --shell /bin/bash --home /home/${OSSH_USER} --gecos "OsshUser" ${OSSH_USER};echo "${OSSH_USER}:`pwgen`" |chpasswd

USER ${OSSH_USER}

RUN mkdir -p /home/${OSSH_USER}/.ssh&&chmod 700 /home/${OSSH_USER}/.ssh

COPY authorized_keys /home/${OSSH_USER}/.ssh/authorized_keys

USER root

RUN chown ${OSSH_UID}:${OSSH_GID} /home/${OSSH_USER}/.ssh/authorized_keys&&chmod 700 /home/${OSSH_USER}

RUN apt-get -y --purge remove pwgen

EXPOSE 22

CMD  ["/usr/sbin/sshd", "-D"]
